[2024-05-21T20:10:16.838+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T20:10:16.852+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-21T20:05:51.152942+00:00 [queued]>
[2024-05-21T20:10:16.857+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-21T20:05:51.152942+00:00 [queued]>
[2024-05-21T20:10:16.857+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T20:10:16.865+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-05-21 20:05:51.152942+00:00
[2024-05-21T20:10:16.872+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T20:10:16.873+0000] {standard_task_runner.py:63} INFO - Started process 130 to run task
[2024-05-21T20:10:16.873+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'games', 'load_data', 'manual__2024-05-21T20:05:51.152942+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/get_main_games.py', '--cfg-path', '/tmp/tmpw8vhebdx']
[2024-05-21T20:10:16.875+0000] {standard_task_runner.py:91} INFO - Job 613: Subtask load_data
[2024-05-21T20:10:16.903+0000] {task_command.py:426} INFO - Running <TaskInstance: games.load_data manual__2024-05-21T20:05:51.152942+00:00 [running]> on host d8c222996c92
[2024-05-21T20:10:16.955+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T20:05:51.152942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T20:05:51.152942+00:00'
[2024-05-21T20:10:16.956+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T20:10:16.973+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T20:10:16.973+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_matches.py", line 154, in load_data
    df.to_sql('test_games', engine, if_exists='replace', index=False)
                            ^^^^^^
UnboundLocalError: cannot access local variable 'engine' where it is not associated with a value
[2024-05-21T20:10:16.979+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=games, task_id=load_data, execution_date=20240521T200551, start_date=20240521T201016, end_date=20240521T201016
[2024-05-21T20:10:16.987+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 613 for task load_data (cannot access local variable 'engine' where it is not associated with a value; 130)
[2024-05-21T20:10:17.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T20:10:17.017+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T20:10:17.018+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
