[2024-05-11T09:07:47.486+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T09:07:47.499+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_seasons.parser manual__2024-05-11T09:07:46.709449+00:00 [queued]>
[2024-05-11T09:07:47.504+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_seasons.parser manual__2024-05-11T09:07:46.709449+00:00 [queued]>
[2024-05-11T09:07:47.504+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-11T09:07:47.511+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parser> on 2024-05-11 09:07:46.709449+00:00
[2024-05-11T09:07:47.518+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-11T09:07:47.519+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-05-11T09:07:47.519+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_seasons', 'parser', 'manual__2024-05-11T09:07:46.709449+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/get_seasons.py', '--cfg-path', '/tmp/tmpm7o0zgh1']
[2024-05-11T09:07:47.521+0000] {standard_task_runner.py:91} INFO - Job 284: Subtask parser
[2024-05-11T09:07:47.546+0000] {task_command.py:426} INFO - Running <TaskInstance: get_seasons.parser manual__2024-05-11T09:07:46.709449+00:00 [running]> on host 0e92ebb16610
[2024-05-11T09:07:47.603+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_seasons' AIRFLOW_CTX_TASK_ID='parser' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T09:07:46.709449+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T09:07:46.709449+00:00'
[2024-05-11T09:07:47.603+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T09:07:47.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T09:07:47.766+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_id_season.py", line 24, in parser
    content = session.get(uri_get_season['get_season'], params=params, headers=headers).json()['content']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-05-11T09:07:47.773+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_seasons, task_id=parser, execution_date=20240511T090746, start_date=20240511T090747, end_date=20240511T090747
[2024-05-11T09:07:47.785+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 284 for task parser (Expecting value: line 1 column 1 (char 0); 68)
[2024-05-11T09:07:47.812+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T09:07:47.828+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T09:07:47.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
