[2024-05-21T18:59:04.533+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T18:59:04.546+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games.get_matches_step manual__2024-05-21T18:58:58.841098+00:00 [queued]>
[2024-05-21T18:59:04.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games.get_matches_step manual__2024-05-21T18:58:58.841098+00:00 [queued]>
[2024-05-21T18:59:04.551+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T18:59:04.558+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_matches_step> on 2024-05-21 18:58:58.841098+00:00
[2024-05-21T18:59:04.565+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T18:59:04.565+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-05-21T18:59:04.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'games', 'get_matches_step', 'manual__2024-05-21T18:58:58.841098+00:00', '--job-id', '557', '--raw', '--subdir', 'DAGS_FOLDER/get_main_games.py', '--cfg-path', '/tmp/tmp9kpbu13h']
[2024-05-21T18:59:04.567+0000] {standard_task_runner.py:91} INFO - Job 557: Subtask get_matches_step
[2024-05-21T18:59:04.593+0000] {task_command.py:426} INFO - Running <TaskInstance: games.get_matches_step manual__2024-05-21T18:58:58.841098+00:00 [running]> on host 70309da0b19a
[2024-05-21T18:59:04.644+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games' AIRFLOW_CTX_TASK_ID='get_matches_step' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T18:58:58.841098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T18:58:58.841098+00:00'
[2024-05-21T18:59:04.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T19:00:14.601+0000] {logging_mixin.py:188} INFO - 100
[2024-05-21T19:01:15.079+0000] {logging_mixin.py:188} INFO - 200
[2024-05-21T19:02:14.200+0000] {logging_mixin.py:188} INFO - 300
[2024-05-21T19:03:03.065+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T19:03:03.066+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_matches.py", line 132, in get_matches
    df.to_csv('steps/games.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'steps'
[2024-05-21T19:03:03.074+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=games, task_id=get_matches_step, execution_date=20240521T185858, start_date=20240521T185904, end_date=20240521T190303
[2024-05-21T19:03:03.082+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 557 for task get_matches_step (Cannot save file into a non-existent directory: 'steps'; 71)
[2024-05-21T19:03:03.117+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T19:03:03.133+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T19:03:03.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
