[2024-05-23T13:46:40.495+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T13:46:40.507+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-23T13:41:25.082941+00:00 [queued]>
[2024-05-23T13:46:40.511+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-23T13:41:25.082941+00:00 [queued]>
[2024-05-23T13:46:40.511+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-23T13:46:40.518+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-05-23 13:41:25.082941+00:00
[2024-05-23T13:46:40.526+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=331) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T13:46:40.527+0000] {standard_task_runner.py:63} INFO - Started process 333 to run task
[2024-05-23T13:46:40.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'games', 'load_data', 'manual__2024-05-23T13:41:25.082941+00:00', '--job-id', '627', '--raw', '--subdir', 'DAGS_FOLDER/get_main_games.py', '--cfg-path', '/tmp/tmpml6cg6os']
[2024-05-23T13:46:40.528+0000] {standard_task_runner.py:91} INFO - Job 627: Subtask load_data
[2024-05-23T13:46:40.553+0000] {task_command.py:426} INFO - Running <TaskInstance: games.load_data manual__2024-05-23T13:41:25.082941+00:00 [running]> on host 5ad9352cdddc
[2024-05-23T13:46:40.606+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T13:41:25.082941+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T13:41:25.082941+00:00'
[2024-05-23T13:46:40.606+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T13:46:40.626+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2024-05-23T13:46:40.633+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2024-05-23T13:46:41.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T13:46:41.176+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_matches.py", line 168, in load_data
    hook.insert_rows(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 573, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.UndefinedColumn: column "gameweek_compseason_label" of relation "games" does not exist
LINE 1: INSERT INTO games (match_id, gameweek_id, gameweek_compSeaso...
                                                  ^

[2024-05-23T13:46:41.184+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=games, task_id=load_data, execution_date=20240523T134125, start_date=20240523T134640, end_date=20240523T134641
[2024-05-23T13:46:41.192+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 627 for task load_data (column "gameweek_compseason_label" of relation "games" does not exist
LINE 1: INSERT INTO games (match_id, gameweek_id, gameweek_compSeaso...
                                                  ^
; 333)
[2024-05-23T13:46:41.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-23T13:46:41.232+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-23T13:46:41.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
