[2024-03-15T20:10:17.779+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parser.parser manual__2024-03-15T20:10:16.301899+00:00 [queued]>
[2024-03-15T20:10:17.784+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parser.parser manual__2024-03-15T20:10:16.301899+00:00 [queued]>
[2024-03-15T20:10:17.784+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-15T20:10:17.795+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): parser> on 2024-03-15 20:10:16.301899+00:00
[2024-03-15T20:10:17.805+0000] {standard_task_runner.py:57} INFO - Started process 73 to run task
[2024-03-15T20:10:17.808+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'parser', 'parser', 'manual__2024-03-15T20:10:16.301899+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/parser.py', '--cfg-path', '/tmp/tmp9p3wujv8']
[2024-03-15T20:10:17.808+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask parser
[2024-03-15T20:10:18.006+0000] {task_command.py:416} INFO - Running <TaskInstance: parser.parser manual__2024-03-15T20:10:16.301899+00:00 [running]> on host 68e0e2dc44b3
[2024-03-15T20:10:18.054+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parser' AIRFLOW_CTX_TASK_ID='parser' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T20:10:16.301899+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-15T20:10:16.301899+00:00'
[2024-03-15T20:10:43.499+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/steps/pars.py", line 57, in pars
    filepath.parent.mkdir(parents=True, exist_ok=True)
AttributeError: 'str' object has no attribute 'parent'
[2024-03-15T20:10:43.506+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser, task_id=parser, execution_date=20240315T201016, start_date=20240315T201017, end_date=20240315T201043
[2024-03-15T20:10:43.520+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task parser ('str' object has no attribute 'parent'; 73)
[2024-03-15T20:10:43.550+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-15T20:10:43.559+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
